spring:
  application:
    name: trustbroker-samlmock

server:
  port: 7070

management:
  server:
    port: 7071

trustbroker:
  samlmock:
    # RP 
    assertionConsumerServiceUrl: http://localhost:7070/authn/consumer
    idpServiceUrl: http://localhost:7070/auth/saml2/idp/samples
    artifactResolutionServiceUrl: http://localhost:7070/authn/arp
    artifactResolutionIssuer: urn:trustbroker.swiss:idp:SAML-MOCK-1

    # XTB
    tbApplicationUrl: http://localhost:8090
    consumerUrl: ${trustbroker.samlmock.tbApplicationUrl}/api/v1/saml
    metadataUrl: ${trustbroker.samlmock.tbApplicationUrl}/api/v1/metadata
    arpUrl: ${trustbroker.samlmock.tbApplicationUrl}/api/v1/saml/arp
    testRpIssuer: urn:trustbroker.swiss:sp:DEMO-RP-1
    testCpIssuer: urn:trustbroker.swiss:idp:SAML-MOCK-1

logging:
  level:
    root: INFO
